### ISSUE TITLE
about stuffthing_2017.json

### ISSUE THREAD

**Issue by Xu-Huihui** [yliu1229/AlignSeg#1]
Hello, fantastic work!
I want to know where I can find the file of "stuffthing_2017.json"

**Comment by yliu1229** [comment]
Hi there,

Thank you for your appreciation!

I believe the file "stuffthing_2017.json" is under the default folder if you download the COCO-Stuff dataset, you can check "https://github.com/nightrome/cocostuff10k" for more information.

However, this file is not necessary for training nor evaluation of our method, so you can simply forget it :)

Let me know if you have any questions.

Cheers,
Yue

**Comment by yliu1229** [comment]
Hi there,

Thank you for your appreciation!

I believe the file "stuffthing_2017.json" is under the default folder if you download the COCO-Stuff dataset, you can check "https://github.com/nightrome/cocostuff10k" for more information.

However, this file is not necessary for training nor evaluation of our method, so you can simply forget it :)

Let me know if you have any questions.

Cheers,
Yue

**Comment by yliu1229** [comment]
Yes, you are right, I forgot the category merging happened in `coco_data.py`.

I am on summer leave and not with the working station right now, I will get back to you once I confirm where the `stuffthing_2017.json` is located or I can simply upload one in this repo.

Sorry for the inconvenience.
Yue

**Comment by yliu1229** [comment]
Well done! 

The result you have in your re-reproduction is reasonable, and please note that the results reported for COCO-Stuff27 in the paper are based on the “curated” split introduced by IIC, so it would be a bit higher than that on the original dataset.

Cheers,
Yue

**Comment by bio-mlhui** [comment]
Dear Yue,

I 've completely reproduced the results on IIC curated split. Thanks for your help!

Regards,
Huihui

**Comment by Cocomuo** [comment]
> Dear Yue,
> 
> I 've completely reproduced the results on IIC curated split. Thanks for your help!
> 
> Regards, Huihui
Hello:
I would like to ask how you can reproduce the accuracy of 35.1 in the paper for the coco dataset, and the accuracy of my reproduction on this dataset is 33.23. May I ask which parameters need to be modified in the configuration file?
If possible, can you share your replicated code and environment configuration with me?
My email: 2934282178@qq.com
Looking forward to your reply, if you can get your help, I will be grateful!

![Image](https://github.com/user-attachments/assets/1c0db776-1146-4f9a-a8a3-e963bf6faf9a)
